import type { ModelCapabilityMatrix } from '@sirius/core';

export const DEFAULT_MODEL_CATALOG: ModelCapabilityMatrix[] = [
  // ── OpenAI ──────────────────────────────────────────────────────────
  {
    modelId: 'gpt-4o',
    provider: 'openai',
    aliases: ['gpt-4o-2024-08-06'],
    capabilities: {
      chat: true,
      streaming: true,
      tools: true,
      embeddings: false,
      vision: true,
      jsonMode: true,
    },
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    costPer1kInput: 0.0025,
    costPer1kOutput: 0.01,
  },
  {
    modelId: 'gpt-4o-mini',
    provider: 'openai',
    aliases: ['gpt-4o-mini-2024-07-18'],
    capabilities: {
      chat: true,
      streaming: true,
      tools: true,
      embeddings: false,
      vision: true,
      jsonMode: true,
    },
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    costPer1kInput: 0.00015,
    costPer1kOutput: 0.0006,
  },
  {
    modelId: 'gpt-4.1',
    provider: 'openai',
    aliases: [],
    capabilities: {
      chat: true,
      streaming: true,
      tools: true,
      embeddings: false,
      vision: true,
      jsonMode: true,
    },
    contextWindow: 1_047_576,
    maxOutputTokens: 32_768,
  },
  {
    modelId: 'gpt-4.1-mini',
    provider: 'openai',
    aliases: [],
    capabilities: {
      chat: true,
      streaming: true,
      tools: true,
      embeddings: false,
      vision: true,
      jsonMode: true,
    },
    contextWindow: 1_047_576,
    maxOutputTokens: 32_768,
  },
  {
    modelId: 'gpt-4.1-nano',
    provider: 'openai',
    aliases: [],
    capabilities: {
      chat: true,
      streaming: true,
      tools: true,
      embeddings: false,
      vision: true,
      jsonMode: true,
    },
    contextWindow: 1_047_576,
    maxOutputTokens: 32_768,
  },
  {
    modelId: 'o3',
    provider: 'openai',
    aliases: [],
    capabilities: {
      chat: true,
      streaming: true,
      tools: true,
      embeddings: false,
      vision: true,
      jsonMode: true,
    },
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
  },
  {
    modelId: 'o3-mini',
    provider: 'openai',
    aliases: [],
    capabilities: {
      chat: true,
      streaming: true,
      tools: true,
      embeddings: false,
      vision: false,
      jsonMode: true,
    },
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
  },
  {
    modelId: 'text-embedding-3-small',
    provider: 'openai',
    aliases: [],
    capabilities: {
      chat: false,
      streaming: false,
      tools: false,
      embeddings: true,
      vision: false,
      jsonMode: false,
    },
    contextWindow: 8_191,
    maxOutputTokens: 0,
    costPer1kInput: 0.00002,
    costPer1kOutput: 0,
  },
  {
    modelId: 'text-embedding-3-large',
    provider: 'openai',
    aliases: [],
    capabilities: {
      chat: false,
      streaming: false,
      tools: false,
      embeddings: true,
      vision: false,
      jsonMode: false,
    },
    contextWindow: 8_191,
    maxOutputTokens: 0,
    costPer1kInput: 0.00013,
    costPer1kOutput: 0,
  },

  // ── Anthropic ───────────────────────────────────────────────────────
  {
    modelId: 'claude-sonnet-4-20250514',
    provider: 'anthropic',
    aliases: ['claude-sonnet-4'],
    capabilities: {
      chat: true,
      streaming: true,
      tools: true,
      embeddings: false,
      vision: true,
      jsonMode: true,
    },
    contextWindow: 200_000,
    maxOutputTokens: 64_000,
  },
  {
    modelId: 'claude-haiku-3-5',
    provider: 'anthropic',
    aliases: ['claude-3-5-haiku-20241022'],
    capabilities: {
      chat: true,
      streaming: true,
      tools: true,
      embeddings: false,
      vision: false,
      jsonMode: true,
    },
    contextWindow: 200_000,
    maxOutputTokens: 8_192,
  },

  // ── Ollama (common local models) ────────────────────────────────────
  {
    modelId: 'llama3.2',
    provider: 'ollama',
    aliases: ['llama3.2:latest'],
    capabilities: {
      chat: true,
      streaming: true,
      tools: true,
      embeddings: false,
      vision: false,
      jsonMode: true,
    },
    contextWindow: 131_072,
    maxOutputTokens: 8_192,
  },
  {
    modelId: 'mistral',
    provider: 'ollama',
    aliases: ['mistral:latest'],
    capabilities: {
      chat: true,
      streaming: true,
      tools: true,
      embeddings: false,
      vision: false,
      jsonMode: false,
    },
    contextWindow: 32_768,
    maxOutputTokens: 8_192,
  },
  {
    modelId: 'nomic-embed-text',
    provider: 'ollama',
    aliases: [],
    capabilities: {
      chat: false,
      streaming: false,
      tools: false,
      embeddings: true,
      vision: false,
      jsonMode: false,
    },
    contextWindow: 8_192,
    maxOutputTokens: 0,
  },
];
